name: RaizEffects
main: zain.drozal.effects.Main
version: 0.9.0
description: A effect plugin.
author: Raizer
commands:
 effectgui:
  description: Put on flame effect.
 water:
  description: Put on water effect.
 wateroff:
  description: Put off water effect.